esphome:
  name: boikovec-si7021-2

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

# Enable logging
logger:
 # level: VERBOSE

ota:
  password: !secret ota.password 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Boikovec Fallback Hotspot"
    password: "HePlVGRcVEZG"

i2c:
  sda: D5
  scl: D6

http_request:
  useragent: esphome/device
  timeout: 10s

sensor:
  - platform: htu21d
    temperature:
      id: si7021_2_temp
      name: si7021_2_hum
      on_value: 
        then:
          - mqtt.publish_json:
              topic: "Boikovec/boikovec_si7021_2_temp"
              payload: 
                root["data"] = id(si7021_2_temp).state;
                root["write"] = true;      
                root["ispublic"] = true;          
          - http_request.post:
              url: https://us-east-1-1.aws.cloud2.influxdata.com/api/v2/write?org=iot&bucket=iot&precision=s
              headers:
                Authorization: "Token b1B2mmbWp9wnaLJsFOiXna_IeS8PdanJq1MClHZoTOSWmzg8SyiZSkq6Rwx4tCNPcLezg74OJd8BXajwWnfiqQ=="
                Content-Type : "text/plain; charset=utf-8"
                Accept       : "application/json"
              body: !lambda |-
                return ((std::string) "iot,location=boikovec,type=si7021,id=2 temperature=" + std::to_string(id(si7021_2_temp).state));
              verify_ssl: false                       
    humidity:
      id: si7021_2_hum
      name: si7021_2_hum   
      on_value: 
        then:
          - mqtt.publish_json:
              topic: "Boikovec/boikovec_si7021_2_hum"
              payload: 
                root["data"] = id(si7021_2_hum).state;
                root["write"] = true;  
                root["ispublic"] = true;        
          - http_request.post:
              url: https://us-east-1-1.aws.cloud2.influxdata.com/api/v2/write?org=iot&bucket=iot&precision=s
              headers:
                Authorization: "Token b1B2mmbWp9wnaLJsFOiXna_IeS8PdanJq1MClHZoTOSWmzg8SyiZSkq6Rwx4tCNPcLezg74OJd8BXajwWnfiqQ=="
                Content-Type : "text/plain; charset=utf-8"
                Accept       : "application/json"
              body: !lambda |-
                return ((std::string) "iot,location=boikovec,type=si7021,id=2 humidity=" + std::to_string(id(si7021_2_hum).state));
              verify_ssl: false                       
    update_interval: 600s

mqtt:
  broker: mqtt.beebotte.com
  port: 1883
  username: !secret beebotte_iamtkn
  discovery: false
  topic_prefix: Boikovec_ignore2

